find_package(OpenCV QUIET)
find_package(roscpp QUIET)
find_package(gazebo QUIET)
find_package(xacro  QUIET)
find_package(Qt5 COMPONENTS Core Gui Widgets OpenGL QUIET)
find_package(Eigen3 QUIET)
find_package(OpenGL QUIET)
